pipeline {
    agent any

    stages {
        // 1. 소스 코드 체크아웃
        stage('Checkout') {
            steps {
                git url: 'https://github.com/DongHoonzzi/CDPP.git', branch: 'main', credentialsId: 'github_token'
            }
        }

        // 2. Maven 빌드 (Windows에서는 PowerShell을 사용)
        stage('Build') {
            steps {
                powershell 'mvn clean install'
            }
        }

        // 3. Spring Boot 애플리케이션 실행 (Windows에서는 PowerShell을 사용)
        stage('Run Application') {
            steps {
                powershell 'java -jar target/your-app-name-1.0.0.jar --server.port=8081'
            }
        }
    }
}
