pipeline {
    agent any
    stages {
        stage('Checkout SCM') {
            steps {
                git url: 'https://github.com/DongHoonzzi/CDPP.git', branch: 'main', credentialsId: 'github_token'
            }
        }
        // 나머지 단계들...
    }
}
